kind: Service
apiVersion: v1
metadata:
  name: config
spec:
  type: ClusterIP
  selector:
    app: spring-cloud-config
  ports:
  - protocol: TCP
    port: 8888
    targetPort: 8888
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: spring-cloud-config
  labels:
    app: spring-cloud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-cloud
  template:
    metadata:
      labels:
        app: spring-cloud
        version: latest
    spec:
      containers:
      - name: spring-cloud-config
        image: hubtea/spring-cloud-config:latest
        ports:
        - name: http
          containerPort: 8888
